[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
ffi = false
isolate = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]
solc_version = "0.8.26"
evm_version = "cancun"
auto_detect_remappings = false


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
 